runtime: nodejs20

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: npm start
